### ISSUE TITLE
v0.2.0 roadmap

### ISSUE THREAD

**Issue by Weldify** [SaveFileLost/Arc#1]
This issue serves as a roadmap to release v0.2.0

- [x] Replicated global state
- [x] Remote Procedure Calls (RPCs)
- [x] Lag compensation
- [x] Bitbuffer network encoding
- [x] Delta network compression

**Comment by Weldify** [comment]
At some point I messed up the wally semantic versioning, so I had to change the version number

**Comment by Weldify** [comment]
Completed
